[package]
name          = "grug-db-disk"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
grug-app   = { path = "../../app" }
grug-jmt   = { path = "../../jellyfish-merkle" }
grug-types = { path = "../../types" }
rocksdb    = { workspace = true }
thiserror  = { workspace = true }

[dev-dependencies]
hex-literal = { workspace = true }
tempfile    = { workspace = true }
