[package]
name          = "grug-vm-wasm"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
data-encoding = { workspace = true }
grug-app      = { path = "../../app" }
grug-crypto   = { path = "../../crypto" }
grug-types    = { path = "../../types" }
serde         = { workspace = true }
thiserror     = { workspace = true }
tracing       = { workspace = true }
wasmer        = { workspace = true, features = ["singlepass"] }

[dev-dependencies]
anyhow         = { workspace = true }
grug-bank      = { path = "../../../contracts/bank", features = ["library"] }
grug-db-memory = { path = "../../db/memory" }
grug-testing   = { path = "../../testing" }
