[package]
name          = "grug-crypto"
version       = { workspace = true }
authors       = { workspace = true }
edition       = { workspace = true }
rust-version  = { workspace = true }
documentation = { workspace = true }
repository    = { workspace = true }
license       = { workspace = true }
categories    = { workspace = true }

[dependencies]
bls-signatures = { workspace = true }
digest         = { workspace = true }
ed25519-dalek  = { workspace = true, features = ["batch"] }
k256           = { workspace = true }
p256           = { workspace = true }
signature      = { workspace = true }
thiserror      = { workspace = true }

[dev-dependencies]
rand = { workspace = true }
sha2 = { workspace = true }
