name: JavaScript SDK

on: push

jobs:
  js-sdk-checks:
    name: JavaScript SDK Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          cache: "npm"
          cache-dependency-path: "sdk/js/package-lock.json"
          node-version: "lts/*"

      - name: Install dependencies
        working-directory: sdk/js
        run: npm clean-install

      - name: Typecheck
        working-directory: sdk/js
        run: npm run typecheck

      - name: Build
        working-directory: sdk/js
        run: npm run build

      - name: Test
        working-directory: sdk/js
        run: echo "placeholder"
